# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.py'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install .
        pip install -r requirements-dev.txt
    - name: Collect coverage
      run: |
        coverage run --source=tests,clang_tools -m pytest
        coverage report -m
        coverage html
    - name: Upload coverage reports to Codecov
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
  install:
    strategy:
      matrix:
        # skip version 14 because it failed on ubuntu.
        version: [ 3.9, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12.0.1, 13 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install clang-tools of push event
      run: pip install git+https://github.com/cpp-linter/clang-tools-pip.git@${{ github.ref }}
    - name: Install clang-tools of pull_request event
      if: github.event_name == 'pull_request'
      run: pip install git+https://github.com/cpp-linter/clang-tools-pip.git@${{ github.head_ref }}
    - name: Install clang-tools
      run: |
        clang-tools --install ${{ matrix.version }}
        which clang-format-${{ matrix.version }}
        which clang-tidy-${{ matrix.version }}
    - name: Check clang-tools on Windows
      if: matrix.os == 'windows-latest'
      run: |
        clang-format-${{ matrix.version }}.exe --version
        clang-tidy-${{ matrix.version }}.exe --version
    - name: Check clang-tools on Unix
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        clang-format-${{ matrix.version }} --version
        clang-tidy-${{ matrix.version }} --version
