# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    branches: [main]
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    uses: cpp-linter/.github/.github/workflows/py-publish.yml@main
    secrets: inherit
