name: Renovate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.CPP_LINTER_TOKEN }}
        env:
          RENOVATE_AUTODISCOVER: true
