name: Renovate

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
