name: Updatecli

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run once a day
    - cron: '0 0 * * *'

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install updatecli
        uses: updatecli/updatecli-action@v2

      - name: Diff
        continue-on-error: true
        run: |
          updatecli diff --config updatecli/updatecli.d --values updatecli/values.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.CPP_LINTER_TOEKN }}

      - name: Apply
        if: github.ref == 'refs/heads/main'
        run: |
          updatecli apply --config updatecli/updatecli.d --values updatecli/values.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.CPP_LINTER_TOEKN }}
